ls:
  .d.ts: point.case
  types:
    .ts: point.case
  constants:
    .ts: point.case

  scripts:
    .js: camelCase
  middleware:
    .ts: camelCase
  utils:
    .ts: camelCase

  plugins:
    .ts: kebab-case
  store:
    .ts: camelCase

  components:
    .vue: PascalCase
  repositories:
    .ts: PascalCase

ignore:
  - node_modules
  - .git
  - .github
  - .vscode
  - .nuxt
  - dist
  - coverage
